local AREAS_FORCED = require "lib.Enums.Areas.Areas_Forced"

local AreasWithForcedBattlesList = {
  AREAS_FORCED.CASTLE,
  AREAS_FORCED.DWARVES_VAULT,
  AREAS_FORCED.GREAT_FOREST,
  AREAS_FORCED.GREGMINSTER_2,
  AREAS_FORCED.GREGMINSTER_PALACE_2,
  AREAS_FORCED.KOUAN,
  AREAS_FORCED.LENANKAMP,
  AREAS_FORCED.MAGICIANS_ISLAND,
  AREAS_FORCED.NECLORDS_CASTLE,
  AREAS_FORCED.PANNU_YAKUTA,
  AREAS_FORCED.PIRATES_FORTRESS,
  AREAS_FORCED.ROCKLAND,
  AREAS_FORCED.SEEK_VALLEY,
  AREAS_FORCED.SEIKA,
  AREAS_FORCED.SHASARAZADE,
  AREAS_FORCED.SONIERE_PRISON,
  AREAS_FORCED.TORAN_CASTLE_DUNGEON,
  AREAS_FORCED.WARRIORS_VILLAGE,
}

return AreasWithForcedBattlesList
