local AREAS_RANDOM = require "lib.Enums.Areas.Areas_Random"

local AreasWithRandomBattlesList = {
  AREAS_RANDOM.CAVE_OF_THE_PAST,
  AREAS_RANDOM.DRAGONS_DEN,
  AREAS_RANDOM.DWARF_TRAIL,
  AREAS_RANDOM.DWARVES_VAULT,
  AREAS_RANDOM.GREAT_FOREST,
  AREAS_RANDOM.GREGMINSTER_PALACE_2,
  AREAS_RANDOM.KALEKKA,
  AREAS_RANDOM.LEPANTS_MANSION,
  AREAS_RANDOM.MAGICIANS_ISLAND,
  AREAS_RANDOM.MORAVIA,
  AREAS_RANDOM.MT_SEIFU,
  AREAS_RANDOM.MT_TIGERWOLF,
  AREAS_RANDOM.NECLORDS_CASTLE,
  AREAS_RANDOM.PANNU_YAKUTA,
  AREAS_RANDOM.SCARLETICIA,
  AREAS_RANDOM.SEEK_VALLEY,
  AREAS_RANDOM.SHASARAZADE,
  AREAS_RANDOM.SONIERE_PRISON,
  AREAS_RANDOM.TORAN_CASTLE,
  AREAS_RANDOM.WORLD_MAP_DRAGON_KNIGHT_FORTRESS,
  AREAS_RANDOM.WORLD_MAP_GREGMINSTER,
  AREAS_RANDOM.WORLD_MAP_GREGMINSTER_2,
  AREAS_RANDOM.WORLD_MAP_KIROV,
  AREAS_RANDOM.WORLD_MAP_LORIMAR,
  AREAS_RANDOM.WORLD_MAP_MORAVIA,
  AREAS_RANDOM.WORLD_MAP_PANNU_YAKUTA,
  AREAS_RANDOM.WORLD_MAP_SCARLETICIA,
  AREAS_RANDOM.WORLD_MAP_SEIKA,
}

return AreasWithRandomBattlesList
