local AREAS_ALL = {
  GREGMINSTER = "Gregminster",
  ROCKLAND = "Rockland",
  LENANKAMP = "Lenankamp",
  MAGICIANS_ISLAND = "Magician's Island",
  SARADY = "Sarady",
  MT_TIGERWOLF = "Mt. Tigerwolf",
  GREGMINSTER_PALACE = "Gregminster Palace",
  SEIKA = "Seika",
  KAKU = "Kaku",
  KOUAN = "Kouan",
  GARAN = "Garan",
  GREAT_FOREST = "Great Forest",
  KWABA = "Kwaba",
  DWARF_TRAIL = "Dwarves Trail",
  VILLAGE_OF_THE_DWARVES = "Village of the Dwarves",
  DWARVES_VAULT = "Dwarves Vault",
  VILLAGE_OF_THE_ELVES = "Village of the Elves",
  BURNT_VILLAGE_OF_THE_ELVES = "Burnt Village of the Elves",
  PANNU_YAKUTA = "Pannu Yakuta",
  ANTEI = "Antei",
  TEIEN = "Teien",
  RIKON = "Rikon",
  SONIERRE_PRISON = "Sonierre Prison",
  SCARLETICIA = "Scarleticia",
  NORTHERN_CHECKPOINT = "Northern Checkpoint",
  LORIMAR = "Lorimar",
  DRAGONS_DEN = "Dragon's Den",
  WARRIORS_VILLAGE = "Warrior's Village",
  QLON = "Qlon",
  NECLORDS_CASTLE = "Neclord's Castle",
  SEEK_VALLEY = "Seek Valley",
  DRAGON_KNIGHTS_FORTRESS = "Dragon Knight's Fortress",
  FLYING_GARDEN = "Flying Garden",
  KIROV = "Kirov",
  KALEKKA = "Kalekka",
  SECRET_FACTORY = "Secret Factory",
  MORAVIA = "Moravia",
  VILLAGE_OF_THE_PAST = "Village of the Past",
  BURNT_VILLAGE_OF_THE_PAST = "Burnt Village of the Past",
  SHASAZARADE = "Shasazarade",
  PIRATE_HIDEOUT = "Pirate Hideout",
  TORAN_CASTLE_DUNGEON = "Toran Castle Dungeon",
  CASTLE = "Castle",
  LUIKANS_HERMITAGE = "Luikan's Hermitage",
  GREGMINSTER_2 = "Gregminster #2",
  GREGMINSTER_PALACE_2 = "Gregminster Palace #2",
  WORLD_MAP_GREGMINSTER = "WM Gregminster",
  WORLD_MAP_SEIKA = "WM Seika",
  WORLD_MAP_PANNU_YAKUTA = "WM Pannu Yakuta",
  WORLD_MAP_SCARLETICIA = "WM Scarleticia",
  WORLD_MAP_LORIMAR = "WM Lorimar",
  WORLD_MAP_DRAGON_KNIGHT_FORTRESS = "WM Dragon Knight's Fortress",
  WORLD_MAP_KIROV = "WM Kirov",
  WORLD_MAP_MORAVIA = "WM Moravia",
  WORLD_MAP_VILLAGE_OF_THE_PAST = "WM Village of the Past",
  WORLD_MAP_LAKE_TORAN = "WM Lake Toran",
  WORLD_MAP_LUIKANS_HERTMITAGE = "WM Luikan's Hermitage",
  WORLD_MAP_GREGMINSTER_2 = "WM Gregminster #2",
}

local AREAS_WITH_RANDOM_BATTLES = {}

local AREAS_WITH_FORCED_BATTLES = {}

local AREAS_WITH_RANDOM_AND_FORCED_BATTLES = {}

return {
  AREAS_ALL = AREAS_ALL,
  AREAS_WITH_RANDOM_BATTLES = AREAS_WITH_RANDOM_BATTLES,
  AREAS_WITH_FORCED_BATTLES = AREAS_WITH_FORCED_BATTLES,
  AREAS_WITH_RANDOM_AND_FORCED_BATTLES = AREAS_WITH_RANDOM_AND_FORCED_BATTLES
}
