local Areas = require "lib.Enums.Areas.Areas_All"

local ZoneInfo = {
  [0] = {
    name = Areas.WORLD_MAP_GREGMINSTER,
    [0] = Areas.GREGMINSTER,
    [1] = Areas.ROCKLAND,
    [2] = Areas.LENANKAMP,
    [3] = Areas.MAGICIANS_ISLAND,
    [4] = Areas.SARADY,
    [5] = Areas.KWABA,
    [6] = Areas.MT_SEIFU,
    [7] = Areas.MT_TIGERWOLF,
    [8] = Areas.MT_TIGERWOLF,
    [9] = Areas.GREGMINSTER_PALACE,
  },
  [1] = {
    name = Areas.WORLD_MAP_SEIKA,
    [0] = Areas.SEIKA,
    [1] = Areas.KAKU,
    [2] = Areas.KOUAN,
    [3] = Areas.GARAN,
    [4] = Areas.GREAT_FOREST,
    [5] = Areas.GREAT_FOREST,
    [7] = Areas.KWABA,
  },
  [2] = {
    name = Areas.WORLD_MAP_PANNU_YAKUTA,
    [0] = Areas.DWARF_TRAIL,
    [1] = Areas.VILLAGE_OF_THE_DWARVES,
    [2] = Areas.DWARVES_VAULT,
    [3] = Areas.VILLAGE_OF_THE_ELVES,
    [4] = Areas.BURNT_VILLAGE_OF_THE_ELVES,
    [5] = Areas.PANNU_YAKUTA,
    [6] = Areas.GREAT_FOREST,
    [7] = Areas.DWARF_TRAIL, --Not listed in my spreadsheet
  },
  [3] = {
    name = Areas.WORLD_MAP_SCARLETICIA,
    [0] = Areas.ANTEI,
    [1] = Areas.TEIEN,
    [2] = Areas.RIKON,
    [3] = Areas.SONIERE_PRISON,
    [4] = Areas.SCARLETICIA,
    [5] = Areas.NORTHERN_CHECKPOINT,
    [6] = Areas.GARAN,
    [7] = Areas.LORIMAR,
    [8] = Areas.DRAGONS_DEN,
  },
  [4] = {
    name = Areas.WORLD_MAP_LORIMAR,
    [0] = Areas.WARRIORS_VILLAGE,
    [1] = Areas.CAVE_OF_THE_PAST,
    [2] = Areas.NECLORDS_CASTLE,
    [3] = Areas.LORIMAR,
    [4] = "Cave of the Past (Inaccessible)",
    [5] = Areas.NECLORDS_CASTLE_ENTRANCE,
  },
  [5] = {
    name = Areas.WORLD_MAP_DRAGON_KNIGHT_FORTRESS,
    [0] = Areas.DRAGONS_DEN,
    [1] = Areas.SEEK_VALLEY,
    [2] = Areas.DRAGON_KNIGHTS_FORTRESS,
    [3] = Areas.FLYING_GARDEN,
    [4] = Areas.SEEK_VALLEY,
  },
  [6] = {
    name = Areas.WORLD_MAP_KIROV,
    [0] = Areas.KIROV,
    [1] = Areas.KALEKKA,
    [2] = Areas.SECRET_FACTORY,
    [3] = Areas.KALEKKA,
  },
  [7] = {
    name = Areas.WORLD_MAP_MORAVIA,
    [0] = Areas.MORAVIA,
    [1] = Areas.NORTHERN_CHECKPOINT,
  },
  [8] = {
    name = Areas.WORLD_MAP_VILLAGE_OF_THE_PAST,
    [0] = Areas.VILLAGE_OF_THE_PAST,
    [1] = Areas.BURNT_VILLAGE_OF_THE_PAST,
  },
  [9] = {
    name = Areas.WORLD_MAP_LAKE_TORAN,
    [0] = Areas.SHASARAZADE,
    [1] = Areas.KAKU,
    [2] = Areas.KIROV,
    [3] = Areas.PIRATES_HIDEOUT,
    [4] = Areas.TORAN_CASTLE,
    [5] = Areas.TEIEN,
    [6] = Areas.TORAN_CASTLE,
    [49] = Areas.SHASARAZADE,
  },
  [10] = {
    name = Areas.WORLD_MAP_LUIKANS_HERTMITAGE,
    [0] = Areas.LUIKANS_HERMITAGE,
  },
  [11] = {
    name = Areas.WORLD_MAP_GREGMINSTER_2,
    [0] = Areas.GREGMINSTER_2,
    [1] = Areas.ROCKLAND,
    [2] = Areas.LENANKAMP,
    [3] = Areas.SARADY,
    [4] = Areas.KWABA,
    [5] = Areas.MT_SEIFU,
    [6] = Areas.MT_TIGERWOLF,
    [7] = Areas.MT_TIGERWOLF,
    [8] = Areas.GREGMINSTER_PALACE_2,
  }
}

return ZoneInfo
