local Names = require "lib.Characters.Names"
local Characters = require "lib.Characters.Characters"

local CombatCharacterNamesList = {
	Names.ALEN,
	Names.ANJI,
	Names.ANTONIO,
	Names.BLACKMAN,
	Names.CAMILLE,
	Names.CLEO,
	Names.CLIVE,
	Names.CROWLEY,
	Names.EIKEI,
	Names.EILEEN,
	Names.FLIK,
	Names.FUKIEN,
	Names.FUMA,
	Names.FUTCH,
	Names.FU_SU_LU,
	Names.GEN,
	Names.GON,
	Names.GREMIO,
	Names.GRENSEAL,
	Names.GRIFFITH,
	Names.HELLION,
	Names.HERO,
	Names.HIX,
	Names.HUMPHREY,
	Names.JUPPO,
	Names.KAGE,
	Names.KAI,
	Names.KAMANDOL,
	Names.KANAK,
	Names.KASIM,
	Names.KASUMI,
	Names.KESSLER,
	Names.KIMBERLY,
	Names.KIRKE,
	Names.KIRKIS,
	Names.KREUTZ,
	Names.KRIN,
	Names.KUROMIMI,
	Names.KWANDA,
	Names.LEONARDO,
	Names.LEPANT,
	Names.LESTER,
	Names.LIUKAN,
	Names.LORELAI,
	Names.LOTTE,
	Names.LUC,
	Names.MAAS,
	Names.MACE,
	Names.MEESE,
	Names.MEG,
	Names.MILIA,
	Names.MILICH,
	Names.MINA,
	Names.MOOSE,
	Names.MORGAN,
	Names.MOSE,
	Names.ODESSA,
	Names.PAHN,
	Names.PESMERGA,
	Names.QUINCY,
	Names.RONNIE,
	Names.RUBI,
	Names.SANSUKE,
	Names.SARAH,
	Names.SERGEI,
	Names.SHEENA,
	Names.SONYA,
	Names.STALLION,
	Names.SYDONIA,
	Names.SYLVINA,
	Names.TAGGART,
	Names.TAI_HO,
	Names.TED,
	Names.TENGAAR,
	Names.VALERIA,
	Names.VARKAS,
	Names.VIKTOR,
	Names.WARREN,
	Names.YAM_KOO,
}

local CombatCharacterNames = {
	ALEN = Names.ALEN,
	ANJI = Names.ANJI,
	ANTONIO = Names.ANTONIO,
	BLACKMAN = Names.BLACKMAN,
	CAMILLE = Names.CAMILLE,
	CLEO = Names.CLEO,
	CLIVE = Names.CLIVE,
	CROWLEY = Names.CROWLEY,
	EIKEI = Names.EIKEI,
	EILEEN = Names.EILEEN,
	FLIK = Names.FLIK,
	FUKIEN = Names.FUKIEN,
	FUMA = Names.FUMA,
	FUTCH = Names.FUTCH,
	FU_SU_LU = Names.FU_SU_LU,
	GEN = Names.GEN,
	GON = Names.GON,
	GREMIO = Names.GREMIO,
	GRENSEAL = Names.GRENSEAL,
	GRIFFITH = Names.GRIFFITH,
	HELLION = Names.HELLION,
	HERO = Names.HERO,
	HIX = Names.HIX,
	HUMPHREY = Names.HUMPHREY,
	JUPPO = Names.JUPPO,
	KAGE = Names.KAGE,
	KAI = Names.KAI,
	KAMANDOL = Names.KAMANDOL,
	KANAK = Names.KANAK,
	KASIM = Names.KASIM,
	KASUMI = Names.KASUMI,
	KESSLER = Names.KESSLER,
	KIMBERLY = Names.KIMBERLY,
	KIRKE = Names.KIRKE,
	KIRKIS = Names.KIRKIS,
	KREUTZ = Names.KREUTZ,
	KRIN = Names.KRIN,
	KUROMIMI = Names.KUROMIMI,
	KWANDA = Names.KWANDA,
	LEONARDO = Names.LEONARDO,
	LEPANT = Names.LEPANT,
	LESTER = Names.LESTER,
	LIUKAN = Names.LIUKAN,
	LORELAI = Names.LORELAI,
	LOTTE = Names.LOTTE,
	LUC = Names.LUC,
	MAAS = Names.MAAS,
	MACE = Names.MACE,
	MEESE = Names.MEESE,
	MEG = Names.MEG,
	MILIA = Names.MILIA,
	MILICH = Names.MILICH,
	MINA = Names.MINA,
	MOOSE = Names.MOOSE,
	MORGAN = Names.MORGAN,
	MOSE = Names.MOSE,
	ODESSA = Names.ODESSA,
	PAHN = Names.PAHN,
	PESMERGA = Names.PESMERGA,
	QUINCY = Names.QUINCY,
	RONNIE = Names.RONNIE,
	RUBI = Names.RUBI,
	SANSUKE = Names.SANSUKE,
	SARAH = Names.SARAH,
	SERGEI = Names.SERGEI,
	SHEENA = Names.SHEENA,
	SONYA = Names.SONYA,
	STALLION = Names.STALLION,
	SYDONIA = Names.SYDONIA,
	SYLVINA = Names.SYLVINA,
	TAGGART = Names.TAGGART,
	TAI_HO = Names.TAI_HO,
	TED = Names.TED,
	TENGAAR = Names.TENGAAR,
	VALERIA = Names.VALERIA,
	VARKAS = Names.VARKAS,
	VIKTOR = Names.VIKTOR,
	WARREN = Names.WARREN,
	YAM_KOO = Names.YAM_KOO,
}

local CombatCharacters = {
	[Names.ALEN] = Characters[Names.ALEN],
	[Names.ANJI] = Characters[Names.ANJI],
	[Names.ANTONIO] = Characters[Names.ANTONIO],
	[Names.BLACKMAN] = Characters[Names.BLACKMAN],
	[Names.CAMILLE] = Characters[Names.CAMILLE],
	[Names.CLEO] = Characters[Names.CLEO],
	[Names.CLIVE] = Characters[Names.CLIVE],
	[Names.CROWLEY] = Characters[Names.CROWLEY],
	[Names.EIKEI] = Characters[Names.EIKEI],
	[Names.EILEEN] = Characters[Names.EILEEN],
	[Names.FLIK] = Characters[Names.FLIK],
	[Names.FUKIEN] = Characters[Names.FUKIEN],
	[Names.FUMA] = Characters[Names.FUMA],
	[Names.FUTCH] = Characters[Names.FUTCH],
	[Names.FU_SU_LU] = Characters[Names.FU_SU_LU],
	[Names.GEN] = Characters[Names.GEN],
	[Names.GON] = Characters[Names.GON],
	[Names.GREMIO] = Characters[Names.GREMIO],
	[Names.GRENSEAL] = Characters[Names.GRENSEAL],
	[Names.GRIFFITH] = Characters[Names.GRIFFITH],
	[Names.HELLION] = Characters[Names.HELLION],
	[Names.HERO] = Characters[Names.HERO],
	[Names.HIX] = Characters[Names.HIX],
	[Names.HUMPHREY] = Characters[Names.HUMPHREY],
	[Names.JUPPO] = Characters[Names.JUPPO],
	[Names.KAGE] = Characters[Names.KAGE],
	[Names.KAI] = Characters[Names.KAI],
	[Names.KAMANDOL] = Characters[Names.KAMANDOL],
	[Names.KANAK] = Characters[Names.KANAK],
	[Names.KASIM] = Characters[Names.KASIM],
	[Names.KASUMI] = Characters[Names.KASUMI],
	[Names.KESSLER] = Characters[Names.KESSLER],
	[Names.KIMBERLY] = Characters[Names.KIMBERLY],
	[Names.KIRKE] = Characters[Names.KIRKE],
	[Names.KIRKIS] = Characters[Names.KIRKIS],
	[Names.KREUTZ] = Characters[Names.KREUTZ],
	[Names.KRIN] = Characters[Names.KRIN],
	[Names.KUROMIMI] = Characters[Names.KUROMIMI],
	[Names.KWANDA] = Characters[Names.KWANDA],
	[Names.LEONARDO] = Characters[Names.LEONARDO],
	[Names.LEPANT] = Characters[Names.LEPANT],
	[Names.LESTER] = Characters[Names.LESTER],
	[Names.LIUKAN] = Characters[Names.LIUKAN],
	[Names.LORELAI] = Characters[Names.LORELAI],
	[Names.LOTTE] = Characters[Names.LOTTE],
	[Names.LUC] = Characters[Names.LUC],
	[Names.MAAS] = Characters[Names.MAAS],
	[Names.MACE] = Characters[Names.MACE],
	[Names.MEESE] = Characters[Names.MEESE],
	[Names.MEG] = Characters[Names.MEG],
	[Names.MILIA] = Characters[Names.MILIA],
	[Names.MILICH] = Characters[Names.MILICH],
	[Names.MINA] = Characters[Names.MINA],
	[Names.MOOSE] = Characters[Names.MOOSE],
	[Names.MORGAN] = Characters[Names.MORGAN],
	[Names.MOSE] = Characters[Names.MOSE],
	[Names.ODESSA] = Characters[Names.ODESSA],
	[Names.PAHN] = Characters[Names.PAHN],
	[Names.PESMERGA] = Characters[Names.PESMERGA],
	[Names.QUINCY] = Characters[Names.QUINCY],
	[Names.RONNIE] = Characters[Names.RONNIE],
	[Names.RUBI] = Characters[Names.RUBI],
	[Names.SANSUKE] = Characters[Names.SANSUKE],
	[Names.SARAH] = Characters[Names.SARAH],
	[Names.SERGEI] = Characters[Names.SERGEI],
	[Names.SHEENA] = Characters[Names.SHEENA],
	[Names.SONYA] = Characters[Names.SONYA],
	[Names.STALLION] = Characters[Names.STALLION],
	[Names.SYDONIA] = Characters[Names.SYDONIA],
	[Names.SYLVINA] = Characters[Names.SYLVINA],
	[Names.TAGGART] = Characters[Names.TAGGART],
	[Names.TAI_HO] = Characters[Names.TAI_HO],
	[Names.TED] = Characters[Names.TED],
	[Names.TENGAAR] = Characters[Names.TENGAAR],
	[Names.VALERIA] = Characters[Names.VALERIA],
	[Names.VARKAS] = Characters[Names.VARKAS],
	[Names.VIKTOR] = Characters[Names.VIKTOR],
	[Names.WARREN] = Characters[Names.WARREN],
	[Names.YAM_KOO] = Characters[Names.YAM_KOO],
}

return {
  Names = CombatCharacterNames,
  NamesList = CombatCharacterNamesList,
  Characters = CombatCharacters
}
