local Names = {
	ALEN = "Alen",
	ANJI = "Anji",
	ANTONIO = "Antonio",
	APPLE = "Apple",
	BLACKMAN = "Blackman",
	CAMILLE = "Camille",
	CHANDLER = "Chandler",
	CHAPMAN = "Chapman",
	CLEO = "Cleo",
	CLIVE = "Clive",
	CROWLEY = "Crowley",
	EIKEI = "Eikei",
	EILEEN = "Eileen",
	ESMERALDA = "Esmeralda",
	FLIK = "Flik",
	FUKIEN = "Fukien",
	FUMA = "Fuma",
	FUTCH = "Futch",
	FU_SU_LU = "Fu Su Lu",
	GASPAR = "Gaspar",
	GEN = "Gen",
	GEORGES = "Georges",
	GIOVANNI = "Giovanni",
	GON = "Gon",
	GREMIO = "Gremio",
	GRENSEAL = "Grenseal",
	GRIFFITH = "Griffith",
	HELLION = "Hellion",
	HERO = "Hero",
	HIX = "Hix",
	HUGO = "Hugo",
	HUMPHREY = "Humphrey",
	IVANOV = "Ivanov",
	JABBA = "Jabba",
	JEANE = "Jeane",
	JOSHUA = "Joshua",
	JUPPO = "Juppo",
	KAGE = "Kage",
	KAI = "Kai",
	KAMANDOL = "Kamandol",
	KANAK = "Kanak",
	KASIM = "Kasim",
	KASIOS = "Kasios",
	KASUMI = "Kasumi",
	KESSLER = "Kessler",
	KIMBERLY = "Kimberly",
	KIRKE = "Kirke",
	KIRKIS = "Kirkis",
	KREUTZ = "Kreutz",
	KRIN = "Krin",
	KUN_TO = "Kun To",
	KUROMIMI = "Kuromimi",
	KWANDA = "Kwanda",
	LEDON = "Ledon",
	LEON = "Leon",
	LEONARDO = "Leonardo",
	LEPANT = "Lepant",
	LESTER = "Lester",
	LIUKAN = "Liukan",
	LORELAI = "Lorelai",
	LOTTE = "Lotte",
	LUC = "Luc",
	MAAS = "Maas",
	MACE = "Mace",
	MARCO = "Marco",
	MARIE = "Marie",
	MATHIU = "Mathiu",
	MAX = "Max",
	MEESE = "Meese",
	MEG = "Meg",
	MELODYE = "Melodye",
	MILIA = "Milia",
	MILICH = "Milich",
	MINA = "Mina",
	MOOSE = "Moose",
	MORGAN = "Morgan",
	MOSE = "Mose",
  ODESSA = "Odessa",
	ONIL = "Onil",
	PAHN = "Pahn",
	PESMERGA = "Pesmerga",
	QLON = "Qlon",
	QUINCY = "Quincy",
	ROCK = "Rock",
	RONNIE = "Ronnie",
	RUBI = "Rubi",
	SANCHO = "Sancho",
	SANSUKE = "Sansuke",
	SARAH = "Sarah",
	SERGEI = "Sergei",
	SHEENA = "Sheena",
	SONYA = "Sonya",
	STALLION = "Stallion",
	SYDONIA = "Sydonia",
	SYLVINA = "Sylvina",
	TAGGART = "Taggart",
	TAI_HO = "Tai Ho",
  TED = "Ted",
	TEMPLETON = "Templeton",
	TENGAAR = "Tengaar",
	TESLA = "Tesla",
	VALERIA = "Valeria",
	VARKAS = "Varkas",
	VIKI = "Viki",
	VIKTOR = "Viktor",
	VINCENT = "Vincent",
	WARREN = "Warren",
	WINDOW = "Window",
	YAM_KOO = "Yam Koo",
	ZEN = "Zen",
}

local NamesList = {
	Names.ALEN,
	Names.ANJI,
	Names.ANTONIO,
	Names.APPLE,
	Names.BLACKMAN,
	Names.CAMILLE,
	Names.CHANDLER,
	Names.CHAPMAN,
	Names.CLEO,
	Names.CLIVE,
	Names.CROWLEY,
	Names.EIKEI,
	Names.EILEEN,
	Names.ESMERALDA,
	Names.FLIK,
	Names.FUKIEN,
	Names.FUMA,
	Names.FUTCH,
	Names.FU_SU_LU,
	Names.GASPAR,
	Names.GEN,
	Names.GEORGES,
	Names.GIOVANNI,
	Names.GON,
	Names.GREMIO,
	Names.GRENSEAL,
	Names.GRIFFITH,
	Names.HELLION,
	Names.HERO,
	Names.HIX,
	Names.HUGO,
	Names.HUMPHREY,
	Names.IVANOV,
	Names.JABBA,
	Names.JEANE,
	Names.JOSHUA,
	Names.JUPPO,
	Names.KAGE,
	Names.KAI,
	Names.KAMANDOL,
	Names.KANAK,
	Names.KASIM,
	Names.KASIOS,
	Names.KASUMI,
	Names.KESSLER,
	Names.KIMBERLY,
	Names.KIRKE,
	Names.KIRKIS,
	Names.KREUTZ,
	Names.KRIN,
	Names.KUN_TO,
	Names.KUROMIMI,
	Names.KWANDA,
	Names.LEDON,
	Names.LEON,
	Names.LEONARDO,
	Names.LEPANT,
	Names.LESTER,
	Names.LIUKAN,
	Names.LORELAI,
	Names.LOTTE,
	Names.LUC,
	Names.MAAS,
	Names.MACE,
	Names.MARCO,
	Names.MARIE,
	Names.MATHIU,
	Names.MAX,
	Names.MEESE,
	Names.MEG,
	Names.MELODYE,
	Names.MILIA,
	Names.MILICH,
	Names.MINA,
	Names.MOOSE,
	Names.MORGAN,
	Names.MOSE,
  Names.ODESSA,
	Names.ONIL,
	Names.PAHN,
	Names.PESMERGA,
	Names.QLON,
	Names.QUINCY,
	Names.ROCK,
	Names.RONNIE,
	Names.RUBI,
	Names.SANCHO,
	Names.SANSUKE,
	Names.SARAH,
	Names.SERGEI,
	Names.SHEENA,
	Names.SONYA,
	Names.STALLION,
	Names.SYDONIA,
	Names.SYLVINA,
	Names.TAGGART,
	Names.TAI_HO,
  Names.TED,
	Names.TEMPLETON,
	Names.TENGAAR,
	Names.TESLA,
	Names.VALERIA,
	Names.VARKAS,
	Names.VIKI,
	Names.VIKTOR,
	Names.VINCENT,
	Names.WARREN,
	Names.WINDOW,
	Names.YAM_KOO,
	Names.ZEN,
}

return Names, NamesList
