local AREAS_ALL = require "lib.Enums.Areas.Areas_All"

local AREAS_FORCED = {
  CASTLE = AREAS_ALL.CASTLE,
  DWARVES_VAULT = AREAS_ALL.DWARVES_VAULT,
  GREAT_FOREST = AREAS_ALL.GREAT_FOREST,
  GREGMINSTER_2 = AREAS_ALL.GREGMINSTER_2,
  GREGMINSTER_PALACE_2 = AREAS_ALL.GREGMINSTER_PALACE_2,
  KOUAN = AREAS_ALL.KOUAN,
  LENANKAMP = AREAS_ALL.LENANKAMP,
  MAGICIANS_ISLAND = AREAS_ALL.MAGICIANS_ISLAND,
  NECLORDS_CASTLE = AREAS_ALL.NECLORDS_CASTLE,
  PANNU_YAKUTA = AREAS_ALL.PANNU_YAKUTA,
  PIRATES_HIDEOUT = AREAS_ALL.PIRATES_HIDEOUT,
  ROCKLAND = AREAS_ALL.ROCKLAND,
  SEEK_VALLEY = AREAS_ALL.SEEK_VALLEY,
  SEIKA = AREAS_ALL.SEIKA,
  SHASARAZADE = AREAS_ALL.SHASARAZADE,
  SONIERE_PRISON = AREAS_ALL.SONIERE_PRISON,
  TORAN_CASTLE = AREAS_ALL.TORAN_CASTLE_DUNGEON,
  WARRIORS_VILLAGE = AREAS_ALL.WARRIORS_VILLAGE,
}

return AREAS_FORCED
