local AREAS_ALL = require "lib.Enums.Areas.Areas_All"

return {
  AREAS_ALL.CASTLE,
  AREAS_ALL.DWARVES_VAULT,
  AREAS_ALL.GREAT_FOREST,
  AREAS_ALL.GREGMINSTER_2,
  AREAS_ALL.GREGMINSTER_PALACE_2,
  AREAS_ALL.KOUAN,
  AREAS_ALL.LENANKAMP,
  AREAS_ALL.MAGICIANS_ISLAND,
  AREAS_ALL.NECLORDS_CASTLE,
  AREAS_ALL.PANNU_YAKUTA,
  AREAS_ALL.PIRATES_FORTRESS,
  AREAS_ALL.ROCKLAND,
  AREAS_ALL.SEEK_VALLEY,
  AREAS_ALL.SEIKA,
  AREAS_ALL.SHASARAZADE,
  AREAS_ALL.SONIERE_PRISON,
  AREAS_ALL.TORAN_CASTLE_DUNGEON,
  AREAS_ALL.WARRIORS_VILLAGE,
}
