local AREAS_ALL = require "lib.Enums.Areas.Areas_All"

local AREAS_RANDOM = {
  CAVE_OF_THE_PAST = AREAS_ALL.CAVE_OF_THE_PAST,
  DRAGONS_DEN = AREAS_ALL.DRAGONS_DEN,
  DWARF_TRAIL = AREAS_ALL.DWARF_TRAIL,
  DWARVES_VAULT = AREAS_ALL.DWARVES_VAULT,
  GREAT_FOREST = AREAS_ALL.GREAT_FOREST,
  GREGMINSTER_PALACE_2 = AREAS_ALL.GREGMINSTER_PALACE_2,
  KALEKKA = AREAS_ALL.KALEKKA,
  LEPANTS_MANSION = AREAS_ALL.LEPANTS_MANSION,
  MAGICIANS_ISLAND = AREAS_ALL.MAGICIANS_ISLAND,
  MORAVIA = AREAS_ALL.MORAVIA,
  MT_SEIFU = AREAS_ALL.MT_SEIFU,
  MT_TIGERWOLF = AREAS_ALL.MT_TIGERWOLF,
  NECLORDS_CASTLE = AREAS_ALL.NECLORDS_CASTLE,
  PANNU_YAKUTA = AREAS_ALL.PANNU_YAKUTA,
  SCARLETICIA = AREAS_ALL.SCARLETICIA,
  SEEK_VALLEY = AREAS_ALL.SEEK_VALLEY,
  SHASARAZADE = AREAS_ALL.SHASARAZADE,
  SONIERE_PRISON = AREAS_ALL.SONIERE_PRISON,
  TORAN_CASTLE = AREAS_ALL.TORAN_CASTLE,
  WORLD_MAP_DRAGON_KNIGHT_FORTRESS = AREAS_ALL.WORLD_MAP_DRAGON_KNIGHT_FORTRESS,
  WORLD_MAP_GREGMINSTER = AREAS_ALL.WORLD_MAP_GREGMINSTER,
  WORLD_MAP_GREGMINSTER_2 = AREAS_ALL.WORLD_MAP_GREGMINSTER_2,
  WORLD_MAP_KIROV = AREAS_ALL.WORLD_MAP_KIROV,
  WORLD_MAP_LORIMAR = AREAS_ALL.WORLD_MAP_LORIMAR,
  WORLD_MAP_MORAVIA = AREAS_ALL.WORLD_MAP_MORAVIA,
  WORLD_MAP_PANNU_YAKUTA = AREAS_ALL.WORLD_MAP_PANNU_YAKUTA,
  WORLD_MAP_SCARLETICIA = AREAS_ALL.WORLD_MAP_SCARLETICIA,
  WORLD_MAP_SEIKA = AREAS_ALL.WORLD_MAP_SEIKA,
}

return AREAS_RANDOM
